### ISSUE TITLE
Imersão em problemas para a escolha de um projeto

### ISSUE THREAD

**Issue by thaliaramoss** [Projetos-III-UFPA-2024-4/engenheiros-do-acaii#2]
Atualmente a equipe encontra-se na primeira etapa do Design Thinking, onde estamos discutindo e estudando possíveis problemas em que queremos nos aprofundar para o desenvolvimento de uma solução.

**Comment by gioocunha** [comment]
https://www.figma.com/board/oL3drkaisYzs51HH2FvN1X/Ideia-1%2C-Projetos-III?node-id=0-1&t=KTdzBfiJTP3hF8a4-1
